name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    services:
      postgres: 
        image: postgres:latest
        env:
          POSTGRES_USER: my_user
          POSTGRES_PASSWORD: my_pass
          POSTGRES_DB: querybuilder
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    
    env:
      DB_USERNAME: my_user
      DB_HOST: localhost
      DB_NAME: querybuilder
      DB_PASSWORD: my_pass
      DB_PORT: 5432

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Unit Tests
        run: yarn test
      - name: E2E Tests
        run: yarn test:e2e
      - name: Test Coverage
        run: yarn test:cov
    
    